---
- name: Workstation set-up
  hosts: workstation
  become: true
  become_user: root
  tasks:
    - name: Adding Student user
      ansible.builtin.user:
        name: student
        password: $5$FZdHme.GElC8xy/T$45vf455zBbUvXWlhrEAkZEQjabCyqgPpw.JDPb1Xzu9
        comment: Ansible managed user
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: /home/student/.ssh/id_rsa
        groups: wheel
        append: yes
    - name: Adding hosts to /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.33.51 server1
          192.168.33.52 server2
          192.168.33.53 server3
    - name: Adding hosts to /etc/hosts
      blockinfile:
        path: /home/student/.ssh/config
        create: true
        mode: '0600'
        owner: student
        group: student
        block: |
          Host s1
            Hostname server1
            User    ansible
            IdentityFile ~/.ssh/id_rsa
          Host s2
            Hostname server2
            User    ansible
            IdentityFile ~/.ssh/id_rsa
          Host s3
            Hostname server3
            User    ansible
            IdentityFile ~/.ssh/id_rsa

- name: Lab set-up
  hosts: servers
  become: true
  become_user: root
  tasks:
    - name: Creating ansible user
      ansible.builtin.user:
        name: ansible
        password: $5$EnJDhFKAB5AWftJE$q0/jnnpbfKejIp59RZjb0SYtWSB6Lr4v.UxDhpi04g2
        comment: Ansible managed user
        shell: /bin/bash
        groups: wheel
        append: yes
    - name: Create .ssh directory if it does not exist
      ansible.builtin.file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'
    - name: Copying student SSH key to ansible users on servers
      ansible.builtin.copy:
        src: /home/student/.ssh/id_rsa.pub
        dest: /home/ansible/.ssh/authorized_keys
        owner: ansible
        group: ansible
        mode: '0600'

    